### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-2-baud-jeune#1]
⚠️ Je suis censé noter quoi ? Si je vous donne deux itérations, c'est pas pour finir votre TP au bout de deux semaines. Normalement il faut me fournir un TP en fin de première itération, comme si il n'y en avait pas une deuxième. ===> rédiger votre rapport.

⚠️ Les notions des priorités des opérations sont respectées ? 

👍 Le pattern visiteur semble être compris

**Comment by Andzura** [comment]
Qu'est ce qui manque pour ce Tp?

**Comment by Slashgear** [comment]
Un oublie de relecture, je vais refaire un tour sur les autres TP pour vérifier que je n'en ai pas oublié d'autres.
